version: "3.9"

services:
  deno:
    container_name: df_backend
    image: df_backend
    restart: always
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
      target: base
    ports:
      - "${PORT_BACKEND}:7000"
    env_file:
      - ../src/backend/.env
    depends_on:
      - prometheus
      - redis
  vue:
    container_name: df_frontend
    image: df_frontend
    restart: always
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
      target: base
    ports:
      - "${PORT_FRONTEND}:8000"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: df_cadvisor
    restart: unless-stopped
    mem_limit: 128m
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8081:8080"

  prometheus:
    image: prom/prometheus:v2.48.0
    container_name: df_prometheus
    restart: unless-stopped
    mem_limit: 384m
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=24h'
      - '--storage.tsdb.retention.size=256MB'
      - '--web.enable-lifecycle'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - cadvisor

  redis:
    image: redis:alpine
    container_name: df_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  prometheus_data:
