FROM denoland/deno:latest as base

WORKDIR /domain-forge

COPY . ./

RUN deno cache src/backend/dependencies.ts

CMD ["run", "--allow-net", "--allow-env", "--allow-read","--allow-run","src/backend/server.ts"]
